name: DiscordMerge
database: true
version: '${project.version}'
main: dk.nydt.discordmerge.DiscordMerge
commands:
  link:
    description: Link your Minecraft account with your Discord account
  unlink:
    description: Unlink your Minecraft account from your Discord account
  claim:
    description: Claim your Role on Discord if you have linked your account
